/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package grupo02;

/**
 *
 * @author Juan Federico
 */
public class Interfaz extends javax.swing.JFrame {
     //CREAMOS USUARIO guillermo2
        String usuario1 = "root";
        String password1 = "root";
        /**IMPORTANTE
         * por ahora he puesto mi usuario y contraseña de MySql
         * He creado dos JTextField llamados Usuario y Password
         * Ahí, guillermo deberá introducir el usuario y password
         * cambiad lo de aquí arriba antes de entregarlo!!!
         * (cuando pulse test, q se cargue la contraseña y el usuario y ya ejecute todo de una)
         */

    /**
     * Creates new form Interfaz
     */
    public Interfaz() {
        initComponents();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        loginButton = new javax.swing.JButton();
        usuarioIN = new java.awt.TextField();
        password = new java.awt.TextField();
        scrollOptimizado = new java.awt.ScrollPane();
        scrollPane2 = new java.awt.ScrollPane();
        javax.swing.JLabel fihceroTabLabel = new javax.swing.JLabel();
        javax.swing.JLabel fihceroTabLabel1 = new javax.swing.JLabel();
        scrollPane3 = new java.awt.ScrollPane();
        scrollTabulado = new java.awt.ScrollPane();
        dbCreateButton = new javax.swing.JButton();
        comprobacionText = new javax.swing.JTextField();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        loginButton.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        loginButton.setText("Login");
        loginButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loginButtonMouseClicked(evt);
            }
        });
        loginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginButtonActionPerformed(evt);
            }
        });

        usuarioIN.setText("Usuario");
        usuarioIN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usuarioINActionPerformed(evt);
            }
        });

        password.setText("Contraseña");
        password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordActionPerformed(evt);
            }
        });

        scrollOptimizado.add(scrollPane2);

        fihceroTabLabel.setText("Fichero Tabulado Optimizado");

        fihceroTabLabel1.setText("Fichero Tabulado");

        scrollPane3.add(scrollTabulado);

        dbCreateButton.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        dbCreateButton.setText("Crear Base de Datos");
        dbCreateButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dbCreateButtonMouseClicked(evt);
            }
        });
        dbCreateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dbCreateButtonActionPerformed(evt);
            }
        });

        comprobacionText.setText("Comprobación de la Base de Datos");
        comprobacionText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comprobacionTextActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(usuarioIN, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(password, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(loginButton, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(108, 108, 108)
                        .addComponent(dbCreateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(comprobacionText))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(fihceroTabLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(scrollOptimizado, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fihceroTabLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(31, 31, 31))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(20, 20, 20)
                    .addComponent(scrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(505, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(usuarioIN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(comprobacionText, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(loginButton, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dbCreateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(66, 66, 66)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fihceroTabLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fihceroTabLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrollOptimizado, javax.swing.GroupLayout.PREFERRED_SIZE, 438, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(208, Short.MAX_VALUE)
                    .addComponent(scrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 438, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(20, 20, 20)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void imprimirGlobal(){
        imprimirSakila();
        imprimirWorld();
    }
    private void imprimirSakila(){
        CargarFichero miConexion = new CargarFichero();
        
         long tiempoConsultaPredefinidaSakila = miConexion.medirTiempoConsulta(" SELECT MAX(length), MIN(length) FROM film;", usuario1, password1);
         String textoS1 = String.valueOf(tiempoConsultaPredefinidaSakila);
        jTextArea4.setText(textoS1);
        
        long tiempoConsultaSimpleSakila = miConexion.medirTiempoConsulta("SELECT * FROM actor;SELECT * FROM customer WHERE city = 'London';", usuario1, password1);
        String textoS2 = String.valueOf(tiempoConsultaSimpleSakila);
        jTextArea3.setText(textoS2);
        
        long tiempoConsultaComplejaSakila = miConexion.medirTiempoConsulta("SELECT film.title, actor.first_name, actor.last_nameFROM filmINNER JOIN film_actor ON film.film_id = film_actor.film_idINNER JOIN actor ON film_actor.actor_id = actor.actor_idINNER JOIN inventory ON film.film_id = inventory.film_idINNER JOIN rental ON inventory.inventory_id = rental.inventory_idGROUP BY film.film_idHAVING COUNT(rental.rental_id) > 5;", usuario1, password1);
         String textoS3 = String.valueOf(tiempoConsultaComplejaSakila);
        jTextArea2.setText(textoS3);
        
    }
    
    private void imprimirWorld(){
        CrearBD miConexion = new CrearBD();
        
         long tiempoConsultaPredefinidaWorld = miConexion.medirTiempoConsulta(" SELECT SUM(surface_area) FROM country;", usuario1, password1);
         String textoW1 = String.valueOf(tiempoConsultaPredefinidaWorld);
        jTextArea7.setText(textoW1);
        
        long tiempoConsultaSimpleWorld = miConexion.medirTiempoConsulta("SELECT * FROM country;",usuario1, password1);
        String textoW2 = String.valueOf(tiempoConsultaSimpleWorld);
        jTextArea6.setText(textoW2);
        
        long tiempoConsultaComplejaWorld = miConexion.medirTiempoConsulta("SELECT country.name, language.languageFROM countryINNER JOIN country_language ON country.code = country_language.country_codeINNER JOIN language ON country_language.language = language.languageWHERE country_language.is_official = 'T'GROUP BY country.codeHAVING COUNT(country_language.language) > 3;", usuario1, password1);
         String textoW3 = String.valueOf(tiempoConsultaComplejaWorld);
        jTextArea5.setText(textoW3);
        
    }
    private void loginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginButtonActionPerformed
        imprimirGlobal();
    }//GEN-LAST:event_loginButtonActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {                                      
        
        /*CargarFichero miConexion = new CargarFichero();
        ConnectDB conexionS = new ConnectDB();
        conexionS.conectarSakila();
        ConnectWorlddb conexionW = new ConnectWorlddb();
        conexionW.conectarWorld();
       */ 
    } 
                                         

    private void usuarioINActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usuarioINActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usuarioINActionPerformed

    private void passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordActionPerformed

    private void dbCreateButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dbCreateButtonMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_dbCreateButtonMouseClicked

    private void dbCreateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dbCreateButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dbCreateButtonActionPerformed

    private void comprobacionTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comprobacionTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comprobacionTextActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JTextField comprobacionText;
    private javax.swing.JButton dbCreateButton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JButton loginButton;
    private java.awt.TextField password;
    private java.awt.ScrollPane scrollOptimizado;
    private java.awt.ScrollPane scrollPane2;
    private java.awt.ScrollPane scrollPane3;
    private java.awt.ScrollPane scrollTabulado;
    private java.awt.TextField usuarioIN;
    // End of variables declaration//GEN-END:variables
}
